import Head from "next/head";
import Image from "next/image";
import Header from "../containers/Header";
import Hero from "../containers/Hero";
import Events from "../containers/Events";
import Questionnaire from "../containers/Questionnaire";
import Brands from "../containers/Brands";
import Footer from "../containers/Footer";

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>Test - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Hero />
        <Events />
        <Questionnaire />
        <Brands />
        <Footer />
      </main>
    </div>
  );
}
